# Site settings
title: Rana Naeem
email: naeem@naeemrana.com
description: > # this means to ignore newlines until "baseurl:"
  Rana Naeem is software engineer
baseurl: "http://naplus.github.io" # the subpath of your site, e.g. /blog/
url: "http://naplus.github.io" # the base hostname & protocol for your site
twitter_username: naeemmahmud
github_username:  naeplus

# Build settings
markdown: kramdown
